### ISSUE TITLE
Create tasks in tasks.py to usual tasks

### ISSUE THREAD

**Issue by fabiommendes** [MES20171CodeSchool/cs-server#10]
Vamos editar o arquivo tasks.py para automatizar tarefas comuns:

* [x] consertar o "inv develop"
* [ ] inv run: executa o runserver (c/ redis)
* [ ] inv db: realiza o makemigrations, migrate, check_permissions e check_expired, etc.
* [ ] inv shell: inicializa ipython importando de codeschool.all *
* [ ] mais alguma?

**Comment by ygortgaleno** [comment]
Professor, o que necessariamente é esse check_permissions e esse check_expired?

**Comment by fabiommendes** [comment]
São dois comandos django no manage.py (ex: python3 manage.py check_permissions). Mas para falar a verdade já implementei esse aí :)

**Comment by fabiommendes** [comment]
O codeschool/__init__.py inicializa o redis caso não esteja inicializado. Vamos tirar este hack e mover o código para o task "inv run"
