### ISSUE TITLE
Improve numeric question tests and String question tests

### ISSUE THREAD

**Issue by VictorDeon** [MES20171CodeSchool/cs-server#3]
Criar/Melhorar os testes da app de numeric questions e string questions usando o pytest

**Comment by allanpereiras** [comment]
- [x] Testar Tolerância (fora e dentro)

- [x] Testar Labels  e Help text (Questão sem descrição, descrição muito longa)

- [ ] Testar Edição e Exclusão (Wagtail?)

**Comment by fabiommendes** [comment]
Vamos separar os testes de integração dos unitários. Isso pode ser feito usando o pytest.mark.integration (qualquer teste sem mark a gente considera unitário).

```python
@pytest.mark.integration
def test_something_slow_that_access_the_db():
    ...
```

É possível marcar um módulo inteiro como integração caso sejam muitos testes e faça sentido separar em módulos. O objetivo é ter uma cobertura boa nos testes unitários e nos de integração separadamente.
