### ISSUE TITLE
Support for continuous integration

### ISSUE THREAD

**Issue by VictorDeon** [MES20171CodeSchool/cs-server#5]
Temos que configurar o settings.py para testes na integração contínua. Algumas coisas podem ser difíceis de integrar no Travis (ex. o sandbox do boxed não funciona).

 - [x] travis.yml
 - [x] Análise de cobertura com o coveralls.io
 - [x] Serviço de análise estática de qualidade de código.

**Comment by fabiommendes** [comment]
Podemos desabilitar o sandbox no Codeschool só para testes. Existe uma opção em codeschool.settings.codeschool.CODESCHOOL_SANDBOX.

É lógico que não podemos simplesmente setar ela como False. É possível fazer isto via o módulo Mock ou simplesmente modificando a variável  no codeschool.settings para False quando importar os módulos de teste que precisariam da sandbox.

**Comment by joao18araujo** [comment]
Estamos com dificuldade na integração contínua devido ao fato de que as builds quebram ao rodar os testes devido à falta do python_boxed em /usr/bin/boxed.

![travis](https://cloud.githubusercontent.com/assets/8868365/25407929/9df58ed4-29e2-11e7-85de-adeef229cd81.png)

Sendo essa uma API feita pelo senhor, gostaríamos de um auxílio para resolver isso. Vale ressaltar que a maioria dos integrantes tem tal binário no computador e por isso os testes rodam localmente, contudo, há integrantes que não possuem tal binário nas máquinas e enfrentam localmente o mesmo problema apontado pelo travis.

**Comment by fabiommendes** [comment]
Tentem com a útima versão do dev. Modifiquei o settings para não rodar com
sandbox quando estiver em ambiente de teste.

Para quem quiser instalar local: o boxed precisa de ser instalado como root
*mesmo quando você estiver no virtualenv*. Por isso, instale o boxed como
root fora do
virtualenv também: "sudo pip install boxed"

Em 25 de abril de 2017 18:12, João Vitor Araujo <notifications@github.com>
escreveu:
