### ISSUE TITLE
Create codeschool questions string

### ISSUE THREAD

**Issue by VictorDeon** [MES20171CodeSchool/cs-server#6]
Criar modulo de questões com respostam em string

Funcionalidades:
- [x] Comparação exata
- [x] Ignorar maiúsculas/minúsculas
- [x] Regex
- [x] Ignorar acentos (use o módulo unidecode)
- [x] Melhorar testes unitários

**Comment by allanpereiras** [comment]
![image](https://cloud.githubusercontent.com/assets/3216015/25405747/a383ee20-29da-11e7-9418-b8c958b1da45.png)

**Comment by joao18araujo** [comment]
A validação está funcionando:

Se a resposta for joao o usuário pode inserir maiúsculo ou minúsculo, acentuação que será ignorado e irá passar, por exemplo, joão, João, Joao, joao, ...

Foi isso que entendemos da funcionalidade, me corrija se eu estiver errado, a funcionalidade está testada e passando.

Uma dúvida que surgiu foi na parte do Regex para questão de string. Parte do grupo imaginou que ela serviria para as validações já feitas (maiúsculo/minúsculo e acentos), outra parte imaginou como sendo para validar expressões regulares como, por exemplo:

Admin coloca a regex de e-mail r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)" como resposta da questão e se o usuário responder "email@email.com" a resposta será validada como correta. Qual das duas abordagens é a esperada dessa issue?

**Comment by vitornere** [comment]
> Admin coloca a regex de e-mail r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$)" como resposta da questão e se o usuário responder "email@email.com" a resposta será validada como correta. Qual das duas abordagens é a esperada dessa issue?

Professor disse que é isso
