### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by allanpereiras** [MES20171CodeSchool/cs-server#8]

**Comment by fabiommendes** [comment]
Reorganizar os testes para poder fazer um TDD efetivo:

* [x] Todos testes que usam o banco de dados devem ser marcados como "integration"
* [x] Cada app deve ter pelo menos um módulo de testes unitários e outro de integração

**Comment by vitornere** [comment]
> Cada app deve ter pelo menos um módulo de testes unitários e outro de integração

Cada módulo de integração e unitário deverá ser uma pasta ex.: "integration_tests/" ou um arquivo "integration_tests.py"?

**Comment by fabiommendes** [comment]
Um arquivo.

Na verdade quem vai dizer que se trata de um teste de integração é o
pytest. Podemos fazer

@pytest.mark.integration
def test_some_thing():
    ...

Mas para marcar um módulo inteiro, definimos a variável


pytestmark = pytest.mark.integration


def test_something():
    ...

class TestSomethingElse:
    def test_method1(self):
        ...

2017-05-02 18:13 GMT-03:00 Vitor Nere <notifications@github.com>:
